services:
  - type: web
    name: ig-puppeteer-clean
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: NODE_VERSION
        value: 20.12.2
